services:

  ubuntu:
    image: kevdillman/dillman
    volumes:
      - .:/Source:ro
    working_dir: /Build
    command: cat /etc/os-release

  fedora:
    image: kevdillman/fedora
    volumes:
      - .:/Source:ro
    working_dir: /Build
    command: cat /etc/os-release
